name       : libunarr
version    : 1.0.1
release    : 1
source     :
    - https://github.com/selmf/unarr/archive/v1.0.1.tar.gz : 0098e3f33182d16c13eb21278696651b170360a9a4d1c0214db4bd7882253223
license    : LGPL-3.0-or-later
component  : programming.library
summary    : (lib)unarr is a decompression library for RAR, TAR, ZIP and 7z* archives.
description: |
    (lib)unarr is a decompression library for RAR, TAR, ZIP and 7z* archives.
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
